name: Docker Image CI

on:
  workflow_dispatch:
  release:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git pull --tags
        
      - name: install go
        run: |
          sudo add-apt-repository ppa:longsleep/golang-backports
          sudo apt update
          sudo apt install golang-go

      - name: login docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Login GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: i-curve
          password: ${{ secrets.TOKEN }}

      - name: build docker
        run: make docker

      - name: docker push
        run: make docker-push

      # - name: docker push
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     push: true
      #     tags: |
      #       wjuncurve/filesystem:latest
      #       ghcr.io/i-curve/filesystem:latest
